# FUNDING.yml - GitHub sponsor button configuration
# Copyright (C) 2019 Kaz Nishimura
#
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved. This file is offered as-is, without any warranty.
---
custom:
  - https://salt.bountysource.com/checkout/amount?team=vx68k
