# bitbucket-pipelines.yml - Bitbucket Pipelines configuration
# Copyright (C) 2019 Kaz Nishimura
#
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved.  This file is offered as-is, without any warranty.

# See <https://confluence.atlassian.com/bitbucket/configure-bitbucket-pipelines-yml-792298910.html>
# for details.
---
definitions:
  steps:
    - step: &configure
        name: Configure
        image: kazssym/libvm68k-builder:gcc
        script:
          - autoreconf --install
          - mkdir -p _build
          - cd _build
          - ../configure --prefix=/opt/libvm68k
        artifacts:
          - _build/**
    - step: &test
        name: Test
        image: kazssym/libvm68k-builder:gcc
        script:
          - autoreconf --install
          - mkdir -p _build
          - cd _build
          - make check
        artifacts:
          - _build/**
pipelines:
  branches:
    master:
      - step: *configure
      - step: *test
  pull-requests:
    "**":
      - step: *configure
      - step: *test
